# This is a basic workflow to help you get started with Actions

name: Index Update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_run:
    types: ["completed"]
    workflows:
      - "Create ADR"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Get Repo Info
        uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            return github.rest.repos.get({
               owner: context.repo.owner,
               repo: context.repo.repo,
            })
            
          #result-encoding: string
      - name: Get List
        id: get-adr-list
        env: 
          REMOTE_URL: ${{fromJSON(steps.set-result.outputs.result).data.html_url}}/blob/master
        run: |
          echo 'list<<EOF' >> $GITHUB_OUTPUT
          for i in `find adr -maxdepth 1 -regextype posix-egrep -regex 'adr/[0-9]{3}-.+\.md' | sort` ; do
            echo $i
            echo "* [${i:4:3} ${i:8}]($i) [remote]($REMOTE_URL/$i)"  >> $GITHUB_OUTPUT
          done;
          echo 'EOF' >> $GITHUB_OUTPUT;
      - name: Test README.md
        env:
          README_MD: |
            # [${{fromJSON(steps.set-result.outputs.result).data.name}}](${{fromJSON(steps.set-result.outputs.result).data.html_url}})
          
            ${{fromJSON(steps.set-result.outputs.result).data.description}}
            ## ADRs
            
            ${{steps.get-adr-list.outputs.list}}
            
            ## Info
            - Rendered: ${{fromJSON(steps.set-result.outputs.result).data.homepage}}
            - Updated At: ${{fromJSON(steps.set-result.outputs.result).data.updated_at}}
            - Pushed At: ${{fromJSON(steps.set-result.outputs.result).data.pushed_at}}
        run: |
          echo "$README_MD" > README.md
      - name: Commit Back
        run: |
           git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config user.name "github-actions[bot]"
           git add README.md
           git commit -m "chore(${{ github.workflow }}): Update files by ${{ github.workflow }}" || exit 0 #Nothing to commit -abort succesfully
           git push  
