# This is a basic workflow that is manually triggered

name: Create ADR

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  issues:
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    permissions:
        contents: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: checkout
      uses: actions/checkout@v3
    - name: Extract meta
      id: meta
      env:
        ID: ${{github.event.issue.number}}
        TITLE: ${{github.event.issue.title}}
      run:
        echo "id=$(printf '%03d' "$ID")" >> "$GITHUB_OUTPUT"

        echo "title=$(echo "$TITLE" | sed -e 's/\s\+/_/g' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
        
        echo "fiename=$(echo "adr/$TITLE.md" | sed -e 's/\s\+/_/g' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
    - name: cleanup old
      env:
        F_Id: ${{steps.meta.outputs.id}}
      run: find adr -maxdepth 1 -regextype posix-egrep -regex "adr/{$F_Id}-.+\.md" -type f -delete
    - name: meta.json
      env: 
        JSON: |
          {
            "id": "${{steps.meta.outputs.id}}",
            "title": "${{steps.meta.outputs.title}}",
            "filename": "${{steps.meta.outputs.fiename}}"
          }
      run:
        echo "$JSON" > meta.json
    - name: Template
      uses: release-engineers/action-template@v1
      with:
          source: '.github/workflows/templates/ADR.md.template'
          target: ${{steps.meta.outputs.fiename}}
    - name: Push
      env:
        ID: ${{steps.meta.outputs.id}}
        TITLE: ${{steps.meta.outputs.title}}
        IID: ${{github.event.issue.number}}
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add adr
        git commit -m "chore(${{ github.workflow }}): Update ADR #$IID $ID-$TITLE" --trailer "ref=#$ID" || exit 0 #Nothing to commit -abort succesfully
        git push  
